---
title: "Modelo base - calibraci칩n posterior 2018"
author: "M. Anzarut, F. Gonz치lez, I. Meza, T. Ortiz"
date: "3/1/2021"
output: html_document
params:
  estado:
        value: NAYARIT
  frac: 
        value: 0.15
  adapt_delta: 
        value: 0.95
  simular: 
        value: FALSE
  prop_observado:
        value: 0.995
---

# `r params$estado`

Fracci칩n de muestreo: `r params$frac`

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
estado <- params$estado
source("R/prep_reportes.R")
```



```{r}
print(parametros)
#print(sim_datos)
```

Obtener una muestra

```{r}
source("R/funciones_calibracion.R")
candidato <- "AMLO"
muestra_1 <- obtener_muestra_marco(datos_ent, frac = params$frac, seed = 5711, 
                                   partidos = partidos)
sim_datos$y_f <- datos_ent[[candidato]]
muestra_1$y <- muestra_1[["votos"]][[candidato]] 
datos_1 <- c(parametros, muestra_1, sim_datos)
total <- sim_datos$y_f %>% sum()
```

```{r}
ruta <- file.path("./stan/modelo.stan")
modelo <- cmdstan_model(ruta)
modelo_sim_indiv <- cmdstan_model(file.path("./stan/modelo_sim_individual.stan"))
```


```{r, message=FALSE, warning=FALSE}
ajuste <- modelo_sim_indiv$sample(data = datos_1, 
                          seed = 2211,
                          iter_sampling = 1000, iter_warmup = 1000,
                          refresh = 250, 
                          chains = 4, 
                          adapt_delta = params$adapt_delta,
                          max_treedepth = 10,
                          parallel_chains = 4, 
                          show_messages = TRUE)
```


```{r, message=FALSE, warning=FALSE}
ajuste$summary(variables = c("y_out", "beta_0", "beta", "kappa"))
total
```

```{r}
bayesplot::mcmc_hist(ajuste$draws("y_out")) +
  geom_vline(xintercept = total, colour = "red")
```

Otro candidato:

```{r}
candidato <- "RAC"
sim_datos$y_f <- datos_ent[[candidato]]
muestra_1$y <- muestra_1[["votos"]][[candidato]] 
datos_1 <- c(parametros, muestra_1, sim_datos)
total <- sim_datos$y_f %>% sum()
```

```{r, message=FALSE, warning=FALSE}
ajuste <- modelo_sim_indiv$sample(data = datos_1, 
                          seed = 2211,
                          iter_sampling = 1000, iter_warmup = 1000,
                          refresh = 250, 
                          chains = 4, 
                          adapt_delta = params$adapt_delta,
                          max_treedepth = 12,
                          parallel_chains = 4, 
                          show_messages = TRUE)
```


```{r}
draws_df <- ajuste$draws() %>% as_draws_df()
bayesplot::mcmc_hist(ajuste$draws("y_out")) +
  geom_vline(xintercept = total, colour = "red")
```
## Predictiva posterior a nivel casilla

```{r}
set.seed(21321)
en_muestra <- muestra_1$in_sample
fuera_muestra <- datos_ent[en_muestra == 0, ]
muestra_oos <- sample_n(fuera_muestra, 30) %>% 
  select(no_casilla, estrato_df, y_f = any_of(candidato))
sims_casilla <- draws_df %>% as_tibble() %>% 
  select(.draw, contains("y_f_sim")) %>% 
  pivot_longer(cols = contains("y_f_sim")) %>%
  mutate(no_casilla = str_extract(name, pattern = "\\d+")) %>% 
  mutate(no_casilla = as.integer(no_casilla))
sims_oos <- muestra_oos %>% left_join(sims_casilla, by = "no_casilla")
ggplot(sims_oos, aes(x = value)) +
  geom_histogram(fill = "salmon") +
  facet_wrap(~no_casilla) +
  geom_vline(aes(xintercept = y_f)) +
  theme_minimal()
```




## Verificaci칩n posterior para total de votos

```{r}
set.seed(8341)
candidato <- "AMLO"
if(params$simular){
  ajuste_muestras_2 <- map(1:100, function(rep){
  muestra_1 <- obtener_muestra_marco(datos_ent, frac = params$frac, 
                                     partidos = partidos, sims_llegadas = sims_llegadas,
                                     prop_obs = params$prop_observado)
  sim_datos$y_f <- datos_ent[[candidato]]
  muestra_1$y <- muestra_1[["votos"]][[candidato]] 
  datos_1 <- c(parametros, muestra_1, sim_datos)
  total <- datos_1$y_f %>% sum()
  print(rep)
  ajuste <- modelo$sample(data = datos_1, 
                          seed = 2131,
                          iter_sampling = 1500, iter_warmup = 1000,
                          refresh = 0, 
                          chains = 6, 
                          adapt_delta = params$adapt_delta,
                          max_treedepth = 12,
                          parallel_chains = 4,
                          show_messages = FALSE)
  y_out_df <- ajuste$draws() %>% as_draws_df()
  rm(ajuste)
  gc()
  y_out_df %>% select(y_out) %>% 
    mutate(rep = rep, total = total)
  })
  write_rds(ajuste_muestras_2, paste0("salidas/ajuste-posterior-muestras","-", estado, ".rds"))
} else {
  ajuste_muestras_2 <- read_rds(paste0("salidas/ajuste-posterior-muestras","-", estado, ".rds"))
}
```

```{r}
ajuste_resumen_tbl <- ajuste_muestras_2 %>% bind_rows() %>% 
  group_by(rep) %>% 
  summarise(sup = quantile(y_out, 0.975), inf = quantile(y_out, 0.025),
            total = first(total))
ggplot(ajuste_resumen_tbl, aes(x = rep, ymin = inf, ymax = sup)) +
  geom_hline(aes(yintercept = total), colour = "salmon") +
  geom_linerange() 
```


```{r}
ajuste_resumen_tbl %>% 
  summarise(cobertura = mean(total >= inf & total <= sup), n = n(), error_porc = mean((sup+inf)/(2*total))) %>% 
  mutate(error = sqrt(cobertura*(1-cobertura)/n))
```

