---
title: "Modelo base conjunto - calibraci칩n posterior 2018"
author: "M. Anzarut, F. Gonz치lez, I. Meza, T. Ortiz"
date: "3/1/2021"
output: html_document
params:
  estado:
    value: NAYARIT
  frac:
    value: 0.15
  adapt_delta:
    value: 0.97
  simular:
    value: TRUE
  n_reps:
    value: 5
  prop_observado:
    value: 0.99
---

# `r params$estado`

Fracci칩n de muestreo: `r params$frac`


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```



```{r}
estado <- params$estado
```


```{r}
source("R/prep_reportes.R", local = knitr::knit_global())
```



```{r}
print(parametros)
#print(sim_datos)
```

Obtener una muestra

```{r}
source("R/funciones_calibracion.R", local = knitr::knit_global())
muestra_1 <- obtener_muestra_marco(datos_ent, frac = params$frac, seed = 1978,  partidos = partidos)
sim_datos$y_f <- datos_ent %>% select(any_of(partidos)) %>% 
  as.matrix()
muestra_1$y <- muestra_1[["votos"]] %>% 
  as.matrix()
muestra_1$p <- length(partidos)
print(length(muestra_1$y))
datos_1 <- c(parametros, muestra_1, sim_datos)
total <- apply(sim_datos$y_f, 2, sum)
prop_votos <- total / sum(total)
```

```{r}
ruta <- file.path("./stan/modelo_conjunto.stan")
md <- cmdstan_model(ruta)
```


```{r, message=FALSE, warning=FALSE}
datos_1$f_bias <- 2.5
datos_1$p_obs <- params$prop_observado
ajuste <- md$sample(data = datos_1, 
                          seed = 21211,
                          iter_sampling = 1500, iter_warmup = 1000,
                          refresh = 250, 
                          chains = 5, 
                          init = 2,
                          adapt_delta = params$adapt_delta,
                          max_treedepth = 12,
                          parallel_chains = 5, 
                          show_messages = TRUE)
```


```{r, message=FALSE, warning=FALSE}
ajuste$summary(variables = c("prop_votos", "beta_0", "beta", "kappa"))
total
ajuste$cmdstan_diagnose()
```

```{r}
ajuste_df <- ajuste$draws("prop_votos") %>% as_draws_df() %>% as_tibble %>% 
  pivot_longer(cols = starts_with("prop_votos"), names_to = "variable",
               values_to = "value")
partidos_df <- tibble(variable = dimnames(ajuste$draws("prop_votos") )$variable,
                      partidos = partidos,
                      prop = prop_votos)
ajuste_df <- left_join(ajuste_df, partidos_df)
ggplot(ajuste_df, aes(x = value)) + 
  facet_wrap(~ partidos, scales = "free_x") +
  geom_histogram() +
  geom_vline(aes(xintercept = prop)) +
  scale_y_sqrt()
```

## Verificaci칩n posterior para porcentaje de votos

```{r}
set.seed(8342)
if(params$simular){
  ajuste_muestras <- map(1:params$n_reps, function(rep){
  muestra_1 <- obtener_muestra_marco(datos_ent, frac = params$frac,
                    partidos = partidos)
  sim_datos$y_f <- datos_ent %>% select(all_of(partidos)) %>% as.matrix()
  muestra_1$y <- muestra_1[["votos"]] %>% as.matrix() 
  muestra_1$p <- ncol(muestra_1$y)
  datos_1 <- c(parametros, muestra_1, sim_datos)
  # sesgo
  datos_1$f_bias <- 2.5
  datos_1$p_obs <- params$prop_observado
  # 
  total <- apply(datos_1$y_f, 2 , sum)
  prop_votos <- total / sum(total)
  print(rep)
  ajuste <- md$sample(data = datos_1, 
                          seed = 21312,
                          iter_sampling = 1500, iter_warmup = 1000,
                          refresh = 0, 
                          chains = 5,
                          init = 2, 
                          adapt_delta = params$adapt_delta,
                          max_treedepth = 12,
                          parallel_chains = 5,
                          show_messages = FALSE)
  y_out_df <- ajuste$draws(c("prop_votos", "y_out")) %>% 
    as_draws_df() %>% as_tibble()
  y_out_df <- y_out_df %>% select(starts_with("prop_votos"), starts_with("y_out")) %>% 
    mutate(rep = rep)
  list(votos = y_out_df, ajuste = ajuste)
  })
  write_rds(ajuste_muestras, 
            paste0("salidas/ajuste-posterior-muestras-conjunto-", 
                   params$estado,"-", params$prop_observado, ".rds"))
} else {
  ajuste_muestras <- read_rds(
    paste0("salidas/ajuste-posterior-muestras-conjunto-", 
                   params$estado, "-", params$prop_observado, ".rds"))
}
```

```{r}
ajuste_muestras_2 <- map(ajuste_muestras, "votos")
ajuste_resumen_tbl <- ajuste_muestras_2 %>% bind_rows() %>%
  pivot_longer(cols = starts_with("prop_votos"), names_to = "variable", values_to = "prop") %>% 
  group_by(rep, variable) %>% 
  summarise(sup = quantile(prop, 0.975), inf = quantile(prop, 0.025)) %>% 
  left_join(partidos_df, by = "variable")  
ggplot(ajuste_resumen_tbl, aes(x = rep, ymin = inf, ymax = sup)) +
  geom_hline(aes(yintercept = prop), colour = "salmon") +
  geom_linerange() + facet_wrap(~ partidos, scales = "free_y") 
```


```{r}
ajuste_resumen_tbl %>% 
  group_by(partidos) %>% 
  summarise(cobertura_inf = mean(prop >= inf), 
            cobertura_sup = mean(prop <= sup), 
            cobertura = mean(prop>= inf  & prop<= sup),
            n = n(),
            precision = mean((sup-inf)/(2))) 
```

