---
title: "Modelo multilogit - calibración posterior 2018"
author: "M. Anzarut, F. González, I. Meza, T. Ortiz"
date: "`r Sys.Date()`"
output: html_document
params:
  estado:
    value: COLIMA
  frac:
    value: 0.20
  adapt_delta:
    value: 0.8
  simular:
    value: TRUE
  n_reps:
    value: 50
  prop_observado:
    value: 0.999
---

# `r params$estado`

Fracción de muestreo: `r params$frac`


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```



```{r}
estado <- params$estado
```


```{r}
covariables <- c("tipo_2", "tipo_3")
source("R/prep_reportes.R", local = knitr::knit_global())
```



```{r}
parametros$kappa_param <- c(1.0, 0.01)
print(parametros)
```

Obtener una muestra

```{r}
#811
#set.seed(83)
set.seed(993)
seeds <- sample.int(9999923, params$n_reps)
source("R/funciones_calibracion.R", local = knitr::knit_global())
muestra_1 <- obtener_muestra_marco(datos_ent, frac = params$frac, 
                                   seed = seeds[97],  partidos = partidos,
                                   sims_llegadas = sims_llegadas, 
                                   prop_obs = params$prop_observado,
                                   id_selec = 15)
sim_datos$y_f <- datos_ent %>% select(any_of(partidos)) %>% 
  as.matrix()
muestra_1$y <- muestra_1[["votos"]] %>% 
  as.matrix()
muestra_1$p <- length(partidos)
dim(muestra_1$y)
datos_1 <- c(parametros, muestra_1, sim_datos)
maximo <- max(abs(datos_1$x_f))
#datos_1$x[] <- 0 #datos_1$x / maximo
#datos_1$x_f[] <- 0 #datos_1$x_f / maximo
total <- apply(sim_datos$y_f, 2, sum)
prop_votos <- total / sum(total)
```

```{r}
ruta <- file.path("./stan/modelo_part_mlogit.stan")
md <- cmdstan_model(ruta)
```


```{r}
datos_1$f_bias <- 10
datos_1$p_obs <- params$prop_observado
ajuste <- md$sample(data = datos_1, 
                          seed = 21312,
                          iter_sampling = 300, iter_warmup = 200,
                          refresh = 100, 
                          chains = 6, 
                          adapt_delta = 0.8,
                          init = 1.0,
                          max_treedepth = 11,
                          step_size = 0.02,
                          parallel_chains = 6, 
                          show_messages = TRUE)
```


```{r, message=FALSE, warning=FALSE}
#ajuste$summary(variables = c("prop_votos", "sigma", "beta_0", "beta", "kappa"))
total
ajuste$cmdstan_diagnose()
```

```{r}
ajuste$summary("participacion") %>% select(q5, q95)
part_obs <- sum(sim_datos$y_f) / sum(sim_datos$n_f)
part_obs
```


```{r, fig.width = 10}
ajuste_df <- ajuste$draws("prop_votos") %>% as_draws_df() %>% as_tibble %>% 
  pivot_longer(cols = starts_with("prop_votos"), names_to = "variable",
               values_to = "value")
partidos_df <- tibble(variable = dimnames(ajuste$draws("prop_votos") )$variable,
                      partidos = partidos,
                      prop = prop_votos)
ajuste_df <- left_join(ajuste_df, partidos_df) %>% 
  group_by(partidos) %>% 
  #mutate(inf = quantile(value, 0.025), sup = quantile(value, 0.975))
  mutate(inf = mean(value) - 2*sd(value), sup = mean(value) + 2*sd(value))
ggplot(ajuste_df, aes(x = value)) + 
  facet_wrap(~ partidos, scales = "free_x") +
  geom_histogram() +
  geom_vline(aes(xintercept = prop)) +
  geom_vline(aes(xintercept = inf, colour = "red")) +
  geom_vline(aes(xintercept = sup, colour = "red")) 
```


```{r, fig.width = 10}
ajuste_df <- ajuste$draws("y_out") %>% as_draws_df() %>% as_tibble %>% 
  pivot_longer(cols = starts_with("y_out"), names_to = "variable",
               values_to = "value")
partidos_df_total <- tibble(variable = dimnames(ajuste$draws("y_out") )$variable,
                      partidos = partidos,
                      prop = total)
ajuste_df <- left_join(ajuste_df, partidos_df_total) %>% 
  group_by(partidos) %>% 
  #mutate(inf = quantile(value, 0.025), sup = quantile(value, 0.975))
  mutate(inf = mean(value) - 2*sd(value), sup = mean(value) + 2*sd(value))
ggplot(ajuste_df, aes(x = value)) + 
  facet_wrap(~ partidos, scales = "free_x") +
  geom_histogram() +
  geom_vline(aes(xintercept = prop)) +
  geom_vline(aes(xintercept = inf, colour = "red")) +
  geom_vline(aes(xintercept = sup, colour = "red")) 
```



## Verificación posterior para porcentaje de votos

```{r, message=FALSE, warning=FALSE, include=FALSE}
if(params$simular){
  ajuste_muestras <- map(1:params$n_reps, function(rep){
  muestra_1 <- obtener_muestra_marco(datos_ent, frac = params$frac,
                    partidos = partidos, sims_llegadas = sims_llegadas, 
                    prop_obs = params$prop_observado, seed = seeds[rep])
  sim_datos$y_f <- datos_ent %>% select(all_of(partidos)) %>% as.matrix()
  ###
  ###
  muestra_1$y <- muestra_1[["votos"]] %>% as.matrix() 
  muestra_1$p <- ncol(muestra_1$y)
  datos_1 <- c(parametros, muestra_1, sim_datos)
  # sesgo
  datos_1$f_bias <- 10
  datos_1$p_obs <- params$prop_observado
  # quitar covariables #########
  #datos_1$x[] <- 0
  #datos_1$x_f[] <- 0 
  ##################
  total <- apply(datos_1$y_f, 2 , sum)
  prop_votos <- total / sum(total)
  print(rep)
  ajuste <- md$sample(data = datos_1, 
                          seed = 21312,
                          iter_sampling = 300, iter_warmup = 200,
                          refresh = 0, 
                          chains = 6,
                          init = 1.0,
                          step_size = 0.02, 
                          adapt_delta = params$adapt_delta,
                          max_treedepth = 11,
                          parallel_chains = 6,
                          show_messages = FALSE)
  y_out_df <- ajuste$draws(c("prop_votos", "y_out", "participacion")) %>% 
    as_draws_df() %>% as_tibble()
  part_df <- y_out_df %>% 
    select(participacion) %>% mutate(rep = rep)
  y_out_df <- y_out_df %>% select(starts_with("prop_votos"), starts_with("y_out")) %>% 
    mutate(rep = rep)
  rm(ajuste)
  gc()
  salida <- list(votos = y_out_df,  participacion = part_df)
  
  })
  write_rds(ajuste_muestras, 
            paste0("salidas/ajuste-posterior-muestras-conjunto-", 
                   params$estado,"-", params$prop_observado, ".rds"))
} else {
  ajuste_muestras <- read_rds(
    paste0("salidas/ajuste-posterior-muestras-conjunto-", 
                   params$estado, "-", params$prop_observado, ".rds"))
}
```

```{r, fig.width=10}
ajuste_muestras_2 <- map(ajuste_muestras, "votos")
ajuste_resumen_tbl <- ajuste_muestras_2 %>% bind_rows() %>%
  pivot_longer(cols = starts_with("prop_votos"), names_to = "variable", values_to = "prop") %>% 
  group_by(rep, variable) %>% 
  #summarise(sup = quantile(prop, 0.975), inf = quantile(prop, 0.025)) %>% 
  summarise(media = mean(prop), ee = sd(prop)) %>% 
  mutate(inf = media - 2 * ee, sup = media + 2 * ee) %>% 
  left_join(partidos_df, by = "variable")  
ggplot(ajuste_resumen_tbl, aes(x = rep, ymin = inf, ymax = sup)) +
  geom_hline(aes(yintercept = prop), colour = "salmon") +
  geom_linerange() + facet_wrap(~ partidos, scales = "free_y") 
```


```{r}
ajuste_resumen_tbl %>% 
  group_by(partidos) %>% 
  summarise(cobertura_inf = mean(prop >= inf), 
            cobertura_sup = mean(prop <= sup), 
            cobertura = mean(prop>= inf  & prop<= sup),
            n = n(),
            precision = mean((sup-inf)/(2))) 
```

## Participación

```{r, fig.width=10}
ajuste_muestras_part <- map(ajuste_muestras, "participacion")
ajuste_resumen_tbl <- ajuste_muestras_part %>% bind_rows() %>%
  group_by(rep) %>% 
  #summarise(sup = quantile(prop, 0.975), inf = quantile(prop, 0.025)) %>% 
  summarise(media = mean(participacion), ee = sd(participacion)) %>% 
  mutate(inf = media - 2 * ee, sup = media + 2 * ee) 
ggplot(ajuste_resumen_tbl, aes(x = rep, ymin = inf, ymax = sup)) +
  geom_hline(yintercept = sum(total) / sum(datos_1$n_f), colour = "salmon") +
  geom_linerange() 
```



```{r}
# ajuste_muestras_2 <- map(ajuste_muestras, "votos")
# ajuste_resumen_tbl <- ajuste_muestras_2 %>% bind_rows() %>%
#   pivot_longer(cols = starts_with("y_out"), names_to = "variable", values_to = "prop") %>% 
#   group_by(rep, variable) %>% 
#   summarise(sup = quantile(prop, 0.975), inf = quantile(prop, 0.025)) %>% 
#   #summarise(media = mean(prop), ee = sd(prop)) %>% 
#   #mutate(inf = media - 2 * ee, sup = media + 2 * ee) %>% 
#   left_join(tibble(partidos = names(total), prop = total, 
#                    variable = dimnames(ajuste$draws("y_out") )$variable ))
# ggplot(ajuste_resumen_tbl, aes(x = rep, ymin = inf, ymax = sup)) +
#   geom_hline(aes(yintercept = prop), colour = "salmon") +
#   geom_linerange() + facet_wrap(~ partidos, scales = "free_y") 
```


```{r}
# ajuste_resumen_tbl %>% 
#   group_by(partidos) %>% 
#   summarise(cobertura_inf = mean(prop >= inf), 
#             cobertura_sup = mean(prop <= sup), 
#             cobertura = mean(prop>= inf  & prop<= sup),
#             n = n(),
#             precision = mean((sup-inf)/(2))) 
```





## Comparación con estimador de razón

```{r, cache=TRUE}
estratos_tbl <- datos_ent %>%
    dplyr::group_by(estrato_df) %>%
    dplyr::summarise(n_stratum = n())
res_razon <- map_df(1:params$n_reps, function(rep){
  muestra_1 <- quickcountmx::select_sample_prop(datos_ent,
                                                stratum = estrato_df,
                                                frac = params$frac, seed = seeds[rep])
  rat_est <- ratio_estimation(muestra_1, data_stratum = estratos_tbl, stratum = estrato_df,
                 n_stratum = n_stratum, any_of(partidos), std_errors = TRUE, B = 200)
  rat_est$rep <- rep
  rat_est
})
```

```{r, fig.width=10}
ggplot(res_razon %>% left_join(partidos_df %>% rename(party = partidos, prop_obs= prop)) %>% 
         filter(rep<=params$n_reps), 
       aes(x = rep, y = prop, ymin= prop-2*std_error, ymax=prop+2*std_error)) +
  geom_linerange() + 
  geom_hline(aes(yintercept = 100*prop_obs), colour = "red") +
  facet_wrap(~ party, scales = "free_y")
```

```{r}
res_razon %>% 
  left_join(partidos_df %>% rename(party = partidos, prop_obs= prop)) %>% 
         filter(rep<=params$n_reps) %>% 
  group_by(party) %>% 
  summarise(cobertura = mean(prop-2*std_error <= 100*prop_obs &
                             prop+2*std_error >= 100*prop_obs),
            precision = 2*mean(std_error))
```

